[book]
authors = ["Martin Geisler"]
language = "en"
multilingual = false
title = "Comprehensive Rust 🦀"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["third_party"]

[preprocessor.svgbob]
renderers = ["html"]
class = "bob"

[output.html]
curly-quotes = true
additional-js = ["speaker-notes.js"]
additional-css = ["svgbob.css", "speaker-notes.css"]
git-repository-url = "https://codeberg.org/mo8it/comprehensive-rust"
git-repository-icon = "fa-code-fork"
edit-url-template = "https://codeberg.org/mo8it/comprehensive-rust/src/branch/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
line-numbers = true

[output.exerciser]
output-directory = "comprehensive-rust-exercises"
